[package]
name = "eLLM"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ellm"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "server"
path = "src/serving/server.rs"

[[bin]]
name = "enhanced-server"
path = "src/serving/enhanced_server.rs"

[[bin]]
name = "batch-server"
path = "src/serving/batch_server.rs"

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py38"], optional = true }
numpy = { version = "0.20", optional = true }
num_cpus = "1.13"
regex = "1.10.2"
core_affinity = "0.8.1"
tokenizers = "0.20.0"
clap = "4.0.29"
rtrb = "0.2.3"
repugnant-pickle = { version = "0.0.1", features = ["torch"] }
anyhow = "1.0.72"
serde = {version = "1.0.192", features = ["derive"]}
serde-pickle = "1.1.1"
serde_json = "1.0.108"
axum = "0.8.4"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
async-stream = "0.3.5"
rand = "0.8.5"
crossbeam = "0.8"
nom = "7.1.3"
zip = "0.6.6"
num-traits="0.2.19"
itertools = "0.14.0"
num = "0.4.3"
safetensors = "0.4.1"
memmap2 = "0.9.4"
half = { version = "2.4.1", features = ["num-traits", "std"] }
# linked-hash-map = "0.5.6"
# hurdles = "1.0.1"
# half  = {version = "2.4.1" , features = ["num-traits", "std"] }
# half  = {version = "2.4.1" , features = [ "std"] }
# zip = { version = "0.6", optional = true }
# repugnant-pickle = { git = "https://github.com/KerfuffleV2/repugnant-pickle", features = ["torch"] }
# smol = "1.3.0"


[build-dependencies]
raw-cpuid = "11.0.2"



[dev-dependencies]
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["html_reports"] }
env_logger = "0.9.0"
approx = "0.5.1"

[toolchain]
channel = "nightly"

[features]
default = []
python = ["pyo3", "numpy"]
