[package]
name = "eLLM"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.13"
regex = "1.10.2"
core_affinity = "0.8.1"
tokenizers = "0.20.0"
clap = "4.0.29"
rtrb = "0.2.3"
repugnant-pickle = { version = "0.0.1", features = ["torch"] }
anyhow = "1.0.72"
serde = {version = "1.0.192", features = ["derive"]}
serde-pickle = "1.1.1"
serde_json = "1.0.108"
nom = "7.1.3"
zip = "0.6.6"
num-traits="0.2.19"
itertools = "0.14.0"
num = "0.4.3"
# linked-hash-map = "0.5.6"
# hurdles = "1.0.1"
# half  = {version = "2.4.1" , features = ["num-traits", "std"] }
# half  = {version = "2.4.1" , features = [ "std"] }
# zip = { version = "0.6", optional = true }
# repugnant-pickle = { git = "https://github.com/KerfuffleV2/repugnant-pickle", features = ["torch"] }
# smol = "1.3.0"


[build-dependencies]
raw-cpuid = "11.0.2"



[dev-dependencies]
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["html_reports"] }
env_logger = "0.9.0"
approx = "0.5.1"

[toolchain]
channel = "nightly"

[features]
